version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: simplecrm
      POSTGRES_USER: crmuser
      POSTGRES_PASSWORD: crmpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: leonicus73/simplecrm:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/simplecrm
      SPRING_DATASOURCE_USERNAME: crmuser
      SPRING_DATASOURCE_PASSWORD: crmpass

volumes:
  pgdata:
